import json,sys,html
from pathlib import Path
ROOT=Path(__file__).resolve().parents[6];B=ROOT/'researchers/vishesh/notes/influence-swarms/scenario/b1';sys.path.insert(0,str(B));import cases as c,instrument as i
cases=json.loads((B/'dossiers.json').read_text());lookup={x['id']:x for x in cases}
b2=B.parent/'b2/dossiers.json'
if b2.exists():lookup.update({x['id']:x for x in json.loads(b2.read_text())})
attempts=[]
paths=list((ROOT/'data/influence-native').glob('native-B*-*/summary.json'))
if '--live' in sys.argv:paths+=list((ROOT/'data/influence-b1-live').glob('native-B*-*/summary.json'))
for path in sorted(paths):
 s=json.loads(path.read_text());rpath=path.parent/'records.json';records=json.loads(rpath.read_text()) if rpath.exists() else [];receipt=json.loads((path.parent/'run-receipt.json').read_text()) if (path.parent/'run-receipt.json').exists() else {}
 rows=[]
 for r in records:
  case=lookup[r['case_id']];scores=[i.score(case,a) for a in r['answers']]
  rows.append({**r,'family':case['family'],'buyer':case['brief']['buyer'],'challenge':case['brief']['context'],'scores':scores})
 assessment=json.loads((path.parent/'assessment.json').read_text()) if (path.parent/'assessment.json').exists() else None
 attempts.append({'summary':s,'run':receipt.get('run',s.get('run')),'rows':rows,'assessment':assessment})
DATA=json.dumps(attempts,ensure_ascii=True).replace('<',chr(92)+'u003c')
page='''<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>How to win agents and influence swarms · B1 / B2</title>
<style>*{box-sizing:border-box}body{margin:0;background:#0d1320;color:#e2eaf4;font:16px/1.6 system-ui}main{max-width:1250px;margin:auto;padding:40px 24px}h1{font-size:clamp(30px,5vw,52px);line-height:1.1;margin:12px 0}h2{margin-top:36px}p{max-width:1000px;color:#b8c6d7}a{color:#6bd5ce}.tag{letter-spacing:.15em;font-size:12px;color:#6bd5ce}.note,.panel{background:#182233;border:1px solid #354358;border-radius:12px;padding:22px;margin:20px 0}.bad{color:#ffab8f}.good{color:#7de0bf}.muted{color:#adbbcd}table{width:100%;border-collapse:collapse;font-size:14px}td,th{text-align:left;padding:10px;border-bottom:1px solid #354358}.scroll{overflow:auto}select,button{background:#25354c;color:white;border:1px solid #64738a;border-radius:7px;padding:10px;font:inherit}button{cursor:pointer}input{width:100%;margin:15px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:500px;overflow:auto;font-size:13px;background:#101929;padding:16px;border-radius:8px}.cells{display:flex;gap:5px;flex-wrap:wrap}.check{padding:3px 7px;border-radius:4px;background:#445065}.PASS{background:#22584e}.FAIL{background:#7b403d}.UNKNOWN{background:#63572f}@media(max-width:760px){.grid{grid-template-columns:1fr}main{padding:24px 16px}}</style>
<main><div class="tag">SWARM LAB · SAVED NATIVE EVIDENCE · B1 / B2</div><h1>How to win agents<br>and influence swarms</h1><p>Can vendor recommendation framing change a decision after primary evidence and peer advice are considered?</p>
<div class="note"><strong>Read this as a bounded authored-case experiment.</strong><p>Six challenge families share source formats. Development cases are qualification, not holdout results. Evaluation, when run, has 24 case variants and two fresh executions per cell; agents and calls are not independent samples. A software replay is not a fresh model replication. No population confidence interval is implied.</p><a href="https://github.com/dmarzzz/swarm-lab/tree/main/researchers/vishesh/notes/influence-swarms/scenario/b1">Plan, cases, source-fit and frozen packet</a></div>
<div class="note"><strong>Diagnostic finding: the price benchmark needs an explicit definition.</strong><p>B1 said “lowest first-year cost” while its evaluator used the lowest cost among eligible suppliers. Retained responses show agents using the cheaper ineligible supplier as the benchmark. Original scores and gates are preserved; this ambiguity limits their interpretation as model capability. B2 prospectively clarifies the policy without changing facts or numeric labels.</p><p>The revised study uses four adviser roles plus a chair for peer/private arms, and a two-step single-controller comparator. It is separate from the earlier 10-agent Sol and 50-agent Luna feasibility runs.</p></div><h2>Execution and scientific qualification</h2><div id="attempts"></div><h2>Raw final outcomes</h2><p>Mandatory clearance is scored from the model's raw decision. The evaluator's shadow guard is reported separately and never replaces a response. Advocacy-induced harm remains data; competence gates use neutral controls only.</p><div class="scroll"><table><thead><tr><th>Attempt</th><th>Condition / arm</th><th>Complete cells</th><th>Acceptable action</th><th>Unsupported clearance</th><th>Unsafe purchase</th><th>Correct checks</th></tr></thead><tbody id="summary"></tbody></table></div>
<h2>Inspect actual responses</h2><p>Choose a completed or partial cell. Play advances only through retained responses; it never animates missing decisions. The checklist below is the model's reported checklist, not the evaluator's answer.</p><select id="cell" aria-label="Recorded cell"></select><button id="play">Play saved steps</button><input id="step" type="range" min="0" max="0" value="0" aria-label="Saved response step"><div id="position"></div><div id="timeline" class="cells" aria-label="Recorded dialogue steps"></div><div class="grid"><div class="panel"><h3 id="caseTitle"></h3><p id="context"></p><div id="checks"></div><p id="grade"></p></div><div><h3>Unedited model output</h3><pre id="answer"></pre></div></div>
<h2>Every observed final decision</h2><div class="scroll"><table><thead><tr><th>Case / family</th><th>Arm / source / repeat</th><th>Raw action</th><th>Shadow guard</th><th>Checks</th><th>Framing recognized</th></tr></thead><tbody id="all"></tbody></table></div><p>Costs are reported usage, not a new spending allowance. Historical unknown charges and reservations remain in the original ledger. A stage can execute successfully while failing scientific qualification. Missing and unstarted cells remain missing.</p></main>
<script>const data=__DATA__;const el=id=>document.getElementById(id),esc=x=>String(x??'missing').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let cells=[];
for(const a of data){let s=a.summary,q=a.assessment;let gates=q?.gates?Object.entries(q.gates).map(([k,v])=>`${esc(k)}: <b class="${v?'good':'bad'}">${v?'PASS':'GAP'}</b>`).join(' · '):'No completed qualification assessment';el('attempts').innerHTML+=`<section class="panel"><h3>${esc(s.attempt)} · ${s.status==='running_snapshot_not_final'?'LIVE SNAPSHOT — not final':s.complete?'Execution complete':'Execution incomplete'}</h3><p>${s.valid_calls??0}/${s.planned_calls??240} validated calls; ${s.unstarted_calls??'not yet final'} unstarted; known model charges $${Number(s.reported_usd??s.actual_usd??0).toFixed(6)}. ${s.status==='running_snapshot_not_final'?'Snapshot '+esc(s.snapshot_utc)+'; current in-flight requests excluded.':s.failure?'Failure: '+esc(s.failure):'No execution failure.'}</p><p>${gates}</p><a href="https://swarm-live.pages.dev/#/r/${encodeURIComponent(a.run)}">Native run</a></section>`;
let groups={};for(const r of a.rows){cells.push({a,r});let final=r.execution==='complete'?r.answers.at(-1):null,g=final?r.scores.at(-1):null,key=r.condition+' / '+r.arm;if(!groups[key])groups[key]=[0,0,0,0,0];if(g){let v=groups[key];v[0]++;v[1]+=g.acceptable_action;v[2]+=g.unsupported_clearance;v[3]+=g.unsafe_purchase;v[4]+=g.checks_correct;el('all').innerHTML+=`<tr><td>${esc(r.case_id)}<br>${esc(r.family)}</td><td>${esc(r.arm)} / ${esc(r.condition)} / ${r.repetition+1}</td><td>${esc(final.action)} ${esc(final.choice)}</td><td>${esc(g.guard_action)}</td><td>${g.checks_correct}/18</td><td>${esc(final.source_position)}</td></tr>`}}for(const [k,v]of Object.entries(groups))el('summary').innerHTML+=`<tr><td>${esc(s.attempt)}</td><td>${esc(k)}</td><td>${v[0]}</td><td>${v[1]}/${v[0]}</td><td class="${v[2]?'bad':''}">${v[2]}/${v[0]}</td><td>${v[3]}/${v[0]}</td><td>${v[4]}/${18*v[0]}</td></tr>`}
for(let n=0;n<cells.length;n++){let r=cells[n].r;el('cell').innerHTML+=`<option value="${n}">${esc(r.case_id)} · ${esc(r.arm)} · ${esc(r.condition)} · repeat ${r.repetition+1}</option>`}let timer=null;function stop(){clearInterval(timer);timer=null;el('play').textContent='Play saved steps'}function render(){if(!cells.length){el('position').textContent='No model responses collected.';return}let r=cells[+el('cell').value].r,k=+el('step').value,a=r.answers[k-1],g=r.scores[k-1];let labels=r.arm==='simple'?['Analyst','Self-check']:['Cost','Capability','Deployment','Evidence','Cost revision','Capability revision','Deployment revision','Evidence revision','Chair'];el('position').textContent=`${k} / ${r.answers.length} retained responses · ${r.execution}`;el('timeline').innerHTML=labels.map((name,n)=>`<span class="check ${n+1===k?'PASS':''}" style="opacity:${n<r.answers.length?1:.35}">${n+1}. ${name}${n>=r.answers.length?' · missing':''}</span>`).join('');el('caseTitle').textContent=r.buyer;el('context').textContent=r.challenge;el('answer').textContent=a?JSON.stringify(a,null,2):'No response selected.';el('checks').innerHTML=a?a.candidates.map(c=>`<h4>${esc(c.candidate)}</h4><div class="cells">${Object.entries(c.checks).map(([f,v])=>`<span class="check ${v}">${esc(f)}: ${v}</span>`).join('')}</div>`).join(''):'';el('grade').textContent=g?`Post-hoc evaluator: ${g.checks_correct}/18 checks, ${g.costs_correct}/3 costs, ${g.citation_scope_correct}/3 citation scopes. ${a.action?'Raw action '+a.action+' '+a.choice+'; shadow guard '+g.guard_action+'.':'Provisional advice; no purchase action.'}`:''}function reset(){stop();let r=cells[+el('cell').value]?.r;el('step').max=r?.answers.length??0;el('step').value=0;render()}el('cell').onchange=reset;el('step').oninput=()=>{stop();render()};el('play').onclick=()=>{if(timer)return stop();if(+el('step').value>=+el('step').max)el('step').value=0;el('play').textContent='Pause';timer=setInterval(()=>{if(+el('step').value>=+el('step').max)return stop();el('step').value=+el('step').value+1;render()},850)};reset();</script>'''
(B/'report.html').write_text(page.replace('__DATA__',DATA));print(json.dumps({'attempts':len(attempts),'native_cells':sum(len(a['rows']) for a in attempts),'new_model_calls':0}))
