import pathlib,json,hashlib
W=pathlib.Path(__file__).resolve().parents[1];R=pathlib.Path('/tmp/grove-review-2026-10-04-addendum');inv=json.loads((W/'review-2026-10-04/addendum-inventory.json').read_text());files=[f for f in inv['files'] if f['path'].startswith('swarm-of-theseus/')];coverage=[]
for x in files:
 p=R/x['path'];assert hashlib.sha256(p.read_bytes()).hexdigest()==x['sha256']
 suffix=p.suffix
 mode='full substantive source/document review'
 if suffix=='.gz':mode='every archive member/index hash checked; every outcome parsed; S1 event records read programmatically to independently recompute structural claims and label-domain check; raw traces not printed'
 elif p.name=='structural-audit.json':mode='every field checked against independent recomputation of archived S1 evidence'
 elif suffix in ('.json','.yaml'):mode='full config/declarative review; source identity checked against S1 manifest when applicable'
 coverage.append({**x,'review_mode':mode})
F=[
 {'id':'ADD-T-01','severity':'P2','title':'Action-domain validation permits illegal labels while successful reports hardcode invalid=0','project':'swarm-of-theseus','evidence':[{'path':'swarm-of-theseus/src/study.py','line':62,'detail':'validate_solve checks label is a string and case IDs are correct, but never requires label in dax/wug; evidence/result are also not validated locally.'},{'path':'swarm-of-theseus/src/provider.py','line':99,'detail':'The generated output schema treats label as a generic string, so provider structured output does not enforce the legal action set.'},{'path':'swarm-of-theseus/src/runner.py','line':70,'detail':'Completed reports always publish invalid=0.'},{'path':'swarm-of-theseus/README.md','line':49,'detail':'Invalid responses are promised as a secondary endpoint; qualification requires zero invalid records.'}],'impact':'A future model can emit an out-of-domain action that is treated only as incorrect rather than counted as invalid, and its run may still satisfy aggregate competence thresholds. This did not corrupt S1: all 2,592 archived S1 labels independently checked here are legal.','recommendation':'Enforce the legal label enum at both schema and local validation; distinguish invalid action from valid-but-wrong action and report actual invalid counts. Validate any work evidence fields only to the declared contract; do not silently correct reasoning. Add a direct validator unit test, no live inference required.','confidence':'high','verification':'Isolated extraction/execution of validate_solve accepted four not-a-legal-label strings with valid case IDs; no world/model execution.'},
 {'id':'ADD-T-02','severity':'P2','title':'Prospective archive-sufficiency claims need an equivalence criterion','project':'swarm-of-theseus/redesign','evidence':[{'path':'swarm-of-theseus/redesign/DESIGN.md','line':60,'detail':'If transplant matches continuation, report archive sufficiency; if single controller matches swarm, drop a special swarm advantage claim.'},{'path':'swarm-of-theseus/redesign/DESIGN.md','line':56,'detail':'Noninferiority margins are required for stable reward and unaffected-component retention, but matching for portability/single-controller comparisons has no explicit margin or uncertainty criterion.'}],'impact':'A small or imprecise pilot can show no detected gap without establishing portable-archive sufficiency or equivalent performance. The draft is unrun and candid about remaining launch blockers, so this is a prospective design clarification rather than a false reported result.','recommendation':'Before qualification specify a practically meaningful equivalence/noninferiority margin and interval decision rule for portability/controller comparisons, or label their gaps descriptive and any null result inconclusive. Failure to establish a swarm advantage is already enough to withhold that claim; it does not prove equivalence.','confidence':'high'}]
updates=[
 {'finding_id':'EP-02','status':'open; independently confirmed in newly available local source','detail':'Provider still consumes SWARM_MODEL_CONFIG_FILE without binding its canonical resolved configuration to the qualified hash; nominal model is still hardcoded in manifest.'},
 {'finding_id':'EP-03','status':'open; independently confirmed','detail':'Rendering and hub operations remain on the numerical execution path. Current runner differs from executed a773 runner only in two reporting-message strings, so the original finding remains valid.'},
 {'finding_id':'EP-06','status':'substantially resolved for Theseus local export, not closed cross-project','detail':'README, deployment, reviews, configs and implementation source are now local. Archive contains 305 indexed evidence files plus index, all hashes verified. It contains zero Python source files; DEPLOYMENT uses source files to mean evidence ingredients. Executed runner/audit bytes still require the immutable source link/cached pinned version because current copies have documented post-run changes.'},
 {'finding_id':'EP-07','status':'open for v1 interval labeling; interpretation improved','detail':'Latest RESULTS adds a prominent critical-review link and retains all six paired effects. The same 95% bootstrap label persists; the narrow two-mapping design is not transformed into calibrated generality by new prose.'},
 {'finding_id':'EP-08','status':'v1 remains limited; v2 addresses the mechanism prospectively','detail':'New draft explicitly defers mentors until an information/budget-controlled comparison; rolling/frozen archive, transplantation and same-evidence probes prevent a simple more-information contrast from being called cultural emergence. No v2 data exist.'},
 {'finding_id':'EP-11','status':'documentation ambiguity resolved; mechanical binding issue remains','detail':'DEPLOYMENT explicitly explains that receipts retain 586c4768 while implementation is a773ff54, with only qualification status added to README. The preflight still does not bind intended plan/implementation automatically.'},
 {'finding_id':'EP-12','status':'open for static PNG','detail':'Newly exported render.py still draws only recorded frame slots. HTML explicitly marks missing slots; PNG still lacks the promised grey missing markers.'}]
V=json.loads((W/'review-2026-10-04/addendum-theseus-verification.json').read_text())
V.update({'s1_label_domain':{'labels':2592,'invalid':0},'isolated_validator_accepts_illegal_label':True,'executed_runner_and_audit_cached_hashes_match_S1_manifest':True,'post_run_source_deltas':{'src/runner.py':'Two report-message strings now include condition TLDR; numerical execution unchanged.','src/audit.py':'Audits retained frames in failed attempts rather than skipping all failed rows; completed S1 scoring logic unchanged.'}})
O={'scope':'Bounded Theseus delta only; 33 file versions in frozen addendum at2026-10-04T02:58:11.098785+00:00. No later workspace exports followed.','snapshot_path':str(R),'findings':F,'coverage':coverage,'coverage_count':len(coverage),'updates_to_prior_findings':updates,'verified_statistics':V,
'updated_conclusions':[
 'The addendum materially improves both completeness and conceptual honesty. Current README/RESULTS explicitly retain v1 as supplied-procedure transmission and link a same-author critical review; no emergence, novelty or multi-generation mentoring claim is defended.',
 'Independent archive recomputation confirms the new mechanistic critique:36 mentoring edges all originate in founders, none in descendants; all72 repair-post solve requests explicitly disclose the new mapping; seed-bank/repair reuse exactly4 binary vectors;648 total S1 solve requests.',
 'There were72 started trajectories:68 completed and4 failed, plus a separate zero-call setup failure. Calls total1697; usage totals1305403 input and425511 output tokens match the results. All306 archive members have a305-entry consistent hash index plus the index file itself.',
 'The v2 selective-continuity proposal is substantially stronger: one flagship scheduling task, acquired payoff-equivalent functional conventions, two replacement waves, stable/partially changed branches, rolling/frozen/transplanted archives, retained-members and single-controller controls, intention-to-treat acquisition failures, and a paired lineage/world estimand. Two further tasks are explicitly deferred extensions.',
 'The draft is not launch-ready and does not pretend to be: transition table, horizon, budgets, schemas, utility weights, margins, sample counts, splits and model versions are named launch blockers. Preserve those blockers and public registration requirements; do not turn the improved story into new evidence.',
 'The dominant remaining implementation risks are unchanged runtime-config binding and reporting failures contaminating execution. The bounded addendum adds an action-domain validation defect and a prospective equivalence-claim clarification; it does not invalidate the archived main-pilot numeric results.'
],
'positive_features':[
 'The new critical review separates process quality from scientific novelty and labels its own reviewer independence/read depth accurately.',
 'Redesign measures utility and component-specific adaptability rather than irrelevant phrase survival, and explicitly falsifies stronger swarm/culture interpretations.',
 'Actor ancestry and archive ancestry are separated, departed private contexts must disappear, and every surviving byte needs an access receipt; this is directly responsive to reproducible agent lifecycle concerns.',
 'Evidence archive integrity and preserved failure accounting withstand independent read-only checks.'
],
'limits':['No new model calls, world trajectories, scientific experiments, public writes, or source/evidence edits. Only reading, archive verification, retrospective recomputation and an isolated parser-validation example occurred.','The new literature section reports honest targeted reading levels; those papers were not independently re-read in this bounded addendum.','The v2 proposal has no executable environment and therefore no implementation validity or feasibility outcome; its hypothetical discrimination must be checked only after a separately registered implementation/qualification plan.','No image assets were new in this delta; rendering code was reviewed, not a fresh UI/image run.']}
(W/'review-2026-10-04/addendum-theseus.json').write_text(json.dumps(O,indent=2)+'\n')
print(json.dumps({'path':'review-2026-10-04/addendum-theseus.json','files':len(coverage),'new_findings':len(F),'all_snapshot_hashes_match':True}))
