#!/usr/bin/env python3
"""fd_meta — standard metadata EXPORTS generated from project.yaml + artifacts.yaml + artifacts.lock.json.

  fd export [folder] [--what ro-crate,codemeta,cff | all]     write the generated files (never hand-edit them)

  ro-crate-metadata.json   RO-Crate 1.2 (the stable release the tooling targets; 1.3 of 2026-06 only remaps four
                           Bioschemas URIs) + Process Run Crate 0.6: the project is the root Dataset, every
                           artifact version file a File with the lock's sha256/size/mime, every version's
                           provenance a CreateAction (agent = person or harness, instrument = model, object =
                           ingredients, result = the file, description = prompt).
  codemeta.json            CodeMeta 3.0 SoftwareSourceCode (Software Heritage indexes it).
  CITATION.cff             Citation File Format 1.2.0 (GitHub "Cite this repository", Zenodo).

All three need `license` (RO-Crate requires it on the root); without it the export is skipped with a message.
`stale_exports(folder)` names exports older than project.yaml/artifacts.yaml, for the checker to warn about.
"""
import datetime
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import fd  # noqa: E402  (fd imports this module lazily inside main(), so no cycle at import time)
import artifacts_check as ac  # noqa: E402

try:
    import yaml
except ImportError:  # pragma: no cover
    yaml = None

RO_CONTEXT = "https://w3id.org/ro/crate/1.2/context"
RO_CONFORMS = ["https://w3id.org/ro/crate/1.2", "https://w3id.org/ro/wfrun/process/0.6"]
CODEMETA_CONTEXT = "https://w3id.org/codemeta/3.0"
GENERATED = "generated by `fd export` from project.yaml + artifacts.yaml + artifacts.lock.json; do not edit"
EXPORTS = {"ro-crate": "ro-crate-metadata.json", "codemeta": "codemeta.json", "cff": "CITATION.cff"}
# repostatus.org identifiers for codemeta developmentStatus
DEV_STATUS = {"idea": "concept", "active": "active", "paused": "suspended", "done": "inactive", "archived": "abandoned"}
SPDX_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9.+-]*$")
HARNESS_NAMES = {"claude": "Claude Code", "codex": "Codex CLI", "nanocodex": "nanocodex", "hermes": "Hermes agent"}


def _sources(folder):
    proj, pe, _, pp = fd.load_project(folder)
    data, me, _, mp = ac.load_manifest(folder)
    lock = ac.load_lock(folder) or {}
    return proj, pp, data, mp, (lock.get("entries") or {}), pe + me


def license_ref(lic):
    """-> (id for the root `license`, extra contextual entity or None)"""
    if not lic:
        return None, None
    if lic.startswith("http://") or lic.startswith("https://"):
        return lic, {"@id": lic, "@type": "CreativeWork", "name": "License"}
    if lic.lower() == "proprietary":
        return "#license", {"@id": "#license", "@type": "CreativeWork", "name": "Proprietary", "description": "all rights reserved"}
    if SPDX_RE.match(lic):
        url = "https://spdx.org/licenses/%s" % lic
        return url, {"@id": url, "@type": "CreativeWork", "name": lic, "identifier": lic}
    return None, None


def _person(a, i):
    pid = a.get("orcid") or a.get("url") or "#author-%d" % (i + 1)
    ent = {"@id": pid, "@type": "Person", "name": a["name"]}
    if a.get("email"):
        ent["email"] = a["email"]
    if a.get("url") and pid != a["url"]:
        ent["url"] = a["url"]
    return ent


def _split_name(name):
    """CFF wants given/family for a person; a single token (a handle) is an entity with `name`"""
    parts = name.strip().split()
    if len(parts) >= 2:
        return {"given-names": " ".join(parts[:-1]), "family-names": parts[-1]}
    return {"name": name.strip()}


def _date(proj):
    return proj.get("date_published") or proj.get("created") or datetime.date.today().isoformat()


def ro_crate(folder, proj, data, entries):
    """-> the JSON-LD dict"""
    lic_id, lic_ent = license_ref(proj.get("license"))
    graph, seen = [], set()

    def add(ent):
        if ent and ent["@id"] not in seen:
            seen.add(ent["@id"])
            graph.append(ent)

    add({"@id": "ro-crate-metadata.json", "@type": "CreativeWork", "conformsTo": [{"@id": u} for u in RO_CONFORMS],
         "about": {"@id": "./"}, "description": GENERATED})
    authors = [_person(a, i) for i, a in enumerate(proj.get("authors") or [])]
    root = {"@id": "./", "@type": "Dataset", "name": proj["name"], "description": proj.get("summary") or proj["name"],
            "datePublished": _date(proj), "license": {"@id": lic_id}, "hasPart": [], "mentions": []}
    if proj.get("identifier"):
        root["identifier"] = proj["identifier"]
    if proj.get("tags"):
        root["keywords"] = ", ".join(proj["tags"])
    if authors:
        root["author"] = [{"@id": a["@id"]} for a in authors]
    if (proj.get("links") or {}).get("repo"):
        root["codeRepository"] = proj["links"]["repo"]
    if (proj.get("links") or {}).get("live"):
        root["url"] = proj["links"]["live"]
    for r in proj.get("relations") or []:
        ref = {"@id": "#rel/" + r["ref"].replace(":", "/")}
        add({"@id": ref["@id"], "@type": "CreativeWork", "name": r["ref"], "description": r.get("note") or r["type"].replace("_", " ")})
        key = {"derived_from": "isBasedOn", "part_of": "isPartOf", "supersedes": "supersedes", "depends_on": "isBasedOn", "related": "relatedLink"}[r["type"]]
        root.setdefault(key, []).append(ref)
    graph.append(root)
    add(lic_ent)
    for a in authors:
        add(a)
    harness_ents, model_ents = {}, {}
    for art in (data or {}).get("artifacts") or []:
        if not isinstance(art, dict) or not art.get("id"):
            continue
        rows = [(None, art)] if art.get("path") else []
        rows += [(v, v) for v in art.get("versions") or [] if isinstance(v, dict) and v.get("path")]
        for v, row in rows:
            key = art["id"] if v is None else "%s@%s" % (art["id"], v.get("v"))
            fp = ac.expand(folder, row["path"])
            if not fp or not os.path.isfile(fp):
                continue
            rel = os.path.relpath(fp, folder).replace(os.sep, "/")
            e = entries.get(key) or {}
            fent = {"@id": rel, "@type": "File", "name": "%s%s" % (art.get("title") or art["id"], "" if v is None else " v%s" % v.get("v"))}
            if e.get("mime"):
                fent["encodingFormat"] = e["mime"]
            if e.get("size_bytes") is not None:
                fent["contentSize"] = str(e["size_bytes"])
            if e.get("sha256"):
                fent["sha256"] = e["sha256"]
            add(fent)
            root["hasPart"].append({"@id": rel})
            if v is None:
                continue
            # one CreateAction per version: who, with what, from what, when
            act = {"@id": "#action/%s" % key, "@type": "CreateAction", "name": "%s: v%s" % (art.get("title") or art["id"], v.get("v")),
                   "result": {"@id": rel}, "endTime": v.get("built_at") or v.get("date")}
            if v.get("prompt") or v.get("note"):
                act["description"] = v.get("prompt") or v.get("note")
            by = v.get("by")
            if by in HARNESS_NAMES:
                hid = "#" + by
                harness_ents.setdefault(hid, {"@id": hid, "@type": "SoftwareApplication", "name": HARNESS_NAMES[by]})
                act["agent"] = {"@id": hid}
            elif by == "human" and authors:
                act["agent"] = {"@id": authors[0]["@id"]}
            elif by == "ci":
                harness_ents.setdefault("#ci", {"@id": "#ci", "@type": "SoftwareApplication", "name": "CI"})
                act["agent"] = {"@id": "#ci"}
            if v.get("model"):
                mid = "#model/" + re.sub(r"[^A-Za-z0-9._-]", "-", str(v["model"]))
                model_ents.setdefault(mid, {"@id": mid, "@type": "SoftwareApplication", "name": str(v["model"]), "softwareVersion": str(v["model"])})
                act["instrument"] = {"@id": mid}
            if v.get("session"):
                act["identifier"] = str(v["session"])
            objs = []
            for ing in v.get("ingredients") or []:
                ing = str(ing)
                if ing.startswith("http://") or ing.startswith("https://"):
                    add({"@id": ing, "@type": "CreativeWork", "name": ing})
                    objs.append({"@id": ing})
                    continue
                ip = ac.expand(folder, ing)
                if ip and os.path.isfile(ip):
                    # an input that is in the crate is a data entity, so it must also hang off the root's hasPart
                    irel = os.path.relpath(ip, folder).replace(os.sep, "/")
                    add({"@id": irel, "@type": "File", "name": irel})
                    if {"@id": irel} not in root["hasPart"]:
                        root["hasPart"].append({"@id": irel})
                    objs.append({"@id": irel})
                else:
                    # an input that is not here (git-ignored data, another machine): a contextual entity, by name
                    iid = "#ingredient/" + ing.strip("/")
                    add({"@id": iid, "@type": "CreativeWork", "name": ing})
                    objs.append({"@id": iid})
            if objs:
                act["object"] = objs
            add(act)
            root["mentions"].append({"@id": act["@id"]})
    for ent in list(harness_ents.values()) + list(model_ents.values()):
        add(ent)
    if not root["mentions"]:
        del root["mentions"]
    return {"@context": RO_CONTEXT, "@graph": graph}


def codemeta(proj):
    lic_id, _ = license_ref(proj.get("license"))
    out = {"@context": CODEMETA_CONTEXT, "@type": "SoftwareSourceCode", "name": proj["name"],
           "description": proj.get("summary") or proj["name"], "_generated_by": GENERATED}
    if proj.get("identifier"):
        out["identifier"] = proj["identifier"]
    if lic_id and lic_id != "#license":
        out["license"] = lic_id
    links = proj.get("links") or {}
    if links.get("repo"):
        out["codeRepository"] = links["repo"]
    if links.get("tracker"):
        out["issueTracker"] = links["tracker"]
    if links.get("live"):
        out["url"] = links["live"]
    if proj.get("authors"):
        out["author"] = [{k: v for k, v in (("@type", "Person"), ("name", a["name"]), ("@id", a.get("orcid")), ("email", a.get("email")), ("url", a.get("url"))) if v} for a in proj["authors"]]
    if proj.get("created"):
        out["dateCreated"] = proj["created"]
    if proj.get("date_published"):
        out["datePublished"] = proj["date_published"]
    if proj.get("status") in DEV_STATUS:
        out["developmentStatus"] = "https://www.repostatus.org/#" + DEV_STATUS[proj["status"]]
    if proj.get("tags"):
        out["keywords"] = list(proj["tags"])
    return out


def cff(proj):
    out = {"cff-version": "1.2.0", "message": "If you use this work, please cite it as below.", "title": proj["name"], "type": "software"}
    if proj.get("summary"):
        out["abstract"] = proj["summary"]
    out["authors"] = [_split_name(a["name"]) | ({"orcid": a["orcid"]} if a.get("orcid") else {}) | ({"email": a["email"]} if a.get("email") else {}) | ({"website": a["url"]} if a.get("url") else {})
                      for a in proj.get("authors") or []] or [{"name": proj.get("owner") or "unknown"}]
    out["date-released"] = _date(proj)
    lic = proj.get("license") or ""
    if lic and lic.lower() != "proprietary" and not lic.startswith("http") and SPDX_RE.match(lic):
        out["license"] = lic
    elif lic.startswith("http"):
        out["license-url"] = lic
    links = proj.get("links") or {}
    if links.get("repo"):
        out["repository-code"] = links["repo"]
    if links.get("live"):
        out["url"] = links["live"]
    ident = proj.get("identifier") or ""
    m = re.match(r"^(?:doi:|https?://doi\.org/)?(10\.\d{4,}/\S+)$", ident)
    if m:
        out["doi"] = m.group(1)
    if proj.get("tags"):
        out["keywords"] = list(proj["tags"])
    return out


def export(folder, what="all"):
    """-> (written paths, messages); skips everything when `license` is missing"""
    folder = os.path.realpath(folder)
    proj, pp, data, mp, entries, errors = _sources(folder)
    if not pp or not proj:
        return [], ["no project.yaml in %s" % folder]
    if errors:
        return [], ["fix these first:"] + ["  " + e for e in errors]
    if not proj.get("license"):
        return [], ["project.yaml has no `license`: exports need one (RO-Crate requires it on the root); add e.g. `license: proprietary` or an SPDX id"]
    wanted = set(EXPORTS) if what in ("all", None, "") else {w.strip() for w in what.split(",")}
    bad = wanted - set(EXPORTS)
    if bad:
        return [], ["unknown export(s): %s (choose from %s)" % (", ".join(sorted(bad)), ", ".join(EXPORTS))]
    written = []
    if "ro-crate" in wanted:
        p = os.path.join(folder, EXPORTS["ro-crate"])
        _write(p, json.dumps(ro_crate(folder, proj, data, entries), indent=1, ensure_ascii=False) + "\n")
        written.append(p)
    if "codemeta" in wanted:
        p = os.path.join(folder, EXPORTS["codemeta"])
        _write(p, json.dumps(codemeta(proj), indent=1, ensure_ascii=False) + "\n")
        written.append(p)
    if "cff" in wanted:
        p = os.path.join(folder, EXPORTS["cff"])
        _write(p, "# %s\n" % GENERATED + yaml.safe_dump(cff(proj), sort_keys=False, allow_unicode=True))
        written.append(p)
    return written, []


def _write(path, text):
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf8") as f:
        f.write(text)
    os.replace(tmp, path)


def stale_exports(folder):
    """exports that exist but are older than project.yaml / artifacts.yaml -> warning strings"""
    srcs = [p for p in (fd.project_path(folder), ac.manifest_path(folder)) if p]
    if not srcs:
        return []
    newest = max(os.path.getmtime(p) for p in srcs)
    out = []
    for name in EXPORTS.values():
        p = os.path.join(folder, name)
        if os.path.isfile(p) and os.path.getmtime(p) < newest - 1:
            out.append("%s is older than project.yaml/artifacts.yaml (run `fd export`)" % name)
    return out


def cmd_export(a):
    folder = fd.find_root(a.folder)
    written, msgs = export(folder, a.what)
    for m in msgs:
        print(m)
    for p in written:
        print("wrote %s" % os.path.relpath(p, folder))
    return 0 if written else 1


def add_parser(sub, flag):
    p = sub.add_parser("export", help="write ro-crate-metadata.json, codemeta.json, CITATION.cff from project.yaml (+ lock)")
    flag(p, "folder", nargs="?", default=".")
    flag(p, "--what", default="all", help="comma list of ro-crate, codemeta, cff (default all)")
    p.set_defaults(fn=cmd_export)
