"""Cross-run analysis of discussion-dose v2 runs. Reads saved records only; no model calls.

    python3 src/analyze_v2.py RUN_DIR [RUN_DIR ...] > RESULTS-V2.md

Each RUN_DIR holds a run's manifest.json and episodes.jsonl (the worker's output directory, or the hub's
episodes.jsonl.gz artifact decompressed next to its manifest). Counts use all assigned episodes as the
denominator; invalid episodes are never dropped.
"""
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path
from consistency_v2 import implied
from tasks_v2 import make_world_v2

def load(run_dir):
    d = Path(run_dir); m = json.loads((d / 'manifest.json').read_text())
    rows = [json.loads(l) for l in (d / 'episodes.jsonl').read_text().splitlines()]
    return m, rows

def invalid_cause(r, world):
    ev = r.get('acquisition_events', []) + r.get('events', [])
    f = next((e for e in ev if e['kind'] == 'call_failure'), None)
    if f is None: return 'unknown'
    if f.get('provider_reason'): return 'provider: ' + f['provider_reason']
    resp = [e for e in ev if e['kind'] == 'call_response' and e.get('agent') == f.get('agent') and e['phase'] == f['phase'] and e.get('round') == f.get('round')]
    claims = (resp[-1]['response'] or {}).get('claims') if resp else None
    if isinstance(claims, list):
        keys = [c.get('key') for c in claims]
        dup = [k for k, n in Counter(keys).items() if n > 1]
        if dup: return 'duplicate key (contested fact)' if world['target_key'] in dup else 'duplicate key (other fact)'
        if any(not c.get('sources') for c in claims): return 'claim with empty sources'
    return f.get('validation_reason') or f.get('error') or 'unknown'

def frac(n, d): return f'{n}/{d}'

def main(dirs):
    runs = [load(d) for d in dirs]
    print('# discussion-dose v2: results across runs\n')
    print('Generated by `src/analyze_v2.py` from saved episode records. Counts are out of all assigned episodes in the cell; invalid episodes stay in denominators. Exploratory; not an accepted hypothesis.\n')
    print('## Runs\n\n| Batch | Level | Worlds | Rounds | Episodes | Git commit |\n| --- | --- | --- | --- | --- | --- |')
    for m, rows in runs:
        p = m['params']
        print(f"| {p.get('batch')} | {p['level']} | {p['tasks'][0]}-{p['tasks'][-1]} | {','.join(map(str, p['rounds']))} | {len(rows)} | `{m['git_commit'][:7]}` |")

    print('\n## Round-0 outcomes by level\n\nCalibration runs and the R0 arms of S0. Role columns: agents endorsing the injected value at the R0 probe, out of attack episodes.\n')
    print('| Batch | Level | Clean correct | Attack: attacker win | Attack: correct | Attack: abstain | Invalid (all) | Exposed false | Witness false | Swing false | False memory |')
    print('| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |')
    for m, rows in runs:
        p = m['params']; R0 = [r for r in rows if r['arm']['rounds'] == 0]
        A = [r for r in R0 if r['arm']['attack']]; C = [r for r in R0 if not r['arm']['attack']]
        ev = lambda xs, k: sum(r['evaluation'].get(k, 0) for r in xs)
        print(f"| {p.get('batch')} | {p['level']} | {frac(ev(C,'correct'),len(C))} | {frac(ev(A,'target_win'),len(A))} | {frac(ev(A,'correct'),len(A))} | {frac(ev(A,'abstain'),len(A))} | {frac(ev(R0,'invalid'),len(R0))} | "
              f"{frac(ev(A,'exposed_false_final'),len(A))} | {frac(ev(A,'witness_false_final'),len(A))} | {frac(ev(A,'swing_false_final'),len(A))} | {frac(ev(A,'false_memory_admitted'),len(A))} |")

    print('\n## Discussion dose (runs with more than one dose)\n')
    for m, rows in runs:
        p = m['params']
        if len(p['rounds']) < 2: continue
        print(f"### {p.get('batch')}\n\n| Rounds | Attack: attacker win | Attack: false memory | Attack: invalid | Clean: correct | Clean: invalid | Correct-to-wrong flips (attack) | Wrong-to-correct flips (attack) |")
        print('| --- | --- | --- | --- | --- | --- | --- | --- |')
        for R in p['rounds']:
            A = [r for r in rows if r['arm']['attack'] and r['arm']['rounds'] == R]; C = [r for r in rows if not r['arm']['attack'] and r['arm']['rounds'] == R]
            ev = lambda xs, k: sum(r['evaluation'].get(k, 0) for r in xs)
            cw = sum(f['correct_to_wrong'] for r in A if r['validity']['ok'] for f in r['evaluation']['flips'])
            wc = sum(f['wrong_to_correct'] for r in A if r['validity']['ok'] for f in r['evaluation']['flips'])
            print(f"| {R} | {frac(ev(A,'target_win'),len(A))} | {frac(ev(A,'false_memory_admitted'),len(A))} | {frac(ev(A,'invalid'),len(A))} | {frac(ev(C,'correct'),len(C))} | {frac(ev(C,'invalid'),len(C))} | {cw} | {wc} |")
        print('\nFalse endorsements per checkpoint, attack arms, valid episodes (world: counts at rounds 0..R):\n')
        by = defaultdict(list)
        for r in rows:
            if r['arm']['attack'] and r['validity']['ok']: by[r['task_id']].append((r['arm']['rounds'], [x['false_endorsements'] for x in r['evaluation']['rounds']], r['evaluation']['target_win']))
        for t in sorted(by):
            print(f"- world {t}: " + '; '.join(f"R{R} {''.join(map(str, s))}{' win' if win else ''}" for R, s, win in sorted(by[t])))
        print()

    print('## Invalid episodes by cause\n\n| Batch | Arm | Rounds | Cause |\n| --- | --- | --- | --- |')
    causes = Counter()
    for m, rows in runs:
        p = m['params']
        for r in rows:
            if r['validity']['ok']: continue
            c = invalid_cause(r, make_world_v2(r['task_id'], p['level'])); causes[c] += 1
            print(f"| {p.get('batch')} | {'attack' if r['arm']['attack'] else 'clean'} | {r['arm']['rounds']} | {c} |")
    print('\nTotals: ' + '; '.join(f'{k}: {v}' for k, v in causes.most_common()) + '.\n')

    print('## Vote consistency with own claims (final ballots, valid episodes)\n')
    print("For each final ballot, the task's public rule and objective are applied to the facts that agent endorsed. *Consistent*: the vote is the option those claims imply. *Inconsistent*: they imply a different option. *Incomplete*: the claims omit a fact needed to decide. Checked against ground truth for 1,200 world/value cases (`consistency_v2.py`).\n")
    print('| Batch | Arm | Consistent | Inconsistent | Incomplete |\n| --- | --- | --- | --- | --- |')
    for m, rows in runs:
        p = m['params']; cnt = Counter()
        for r in rows:
            if not r['validity']['ok']: continue
            w = make_world_v2(r['task_id'], p['level']); arm = 'attack' if r['arm']['attack'] else 'clean'
            for b in r['result']['ballots']:
                imp = implied(w, b['claims']); cnt[(arm, 'incomplete' if imp is None else 'consistent' if imp == b['vote'] else 'inconsistent')] += 1
        for arm in ('clean', 'attack'):
            tot = sum(cnt[(arm, k)] for k in ('consistent', 'inconsistent', 'incomplete'))
            print(f"| {p.get('batch')} | {arm} | {frac(cnt[(arm,'consistent')],tot)} | {frac(cnt[(arm,'inconsistent')],tot)} | {frac(cnt[(arm,'incomplete')],tot)} |")

if __name__ == '__main__': main(sys.argv[1:])
