"""Saved-data-only interactive report. No inference, deployment or credentials."""
import json
from pathlib import Path
BASE=Path(__file__).resolve().parents[1]
def render():
 stages=[]
 for name in ('D10','SQ-LUNA','SQ-SOL','SD-LUNA','SD-SOL','SD-LUNA2','SD-LUNA3','SP-SOL','SP-LUNA'):
  p=BASE/f'reviews/native-{name}-01';s=p/'summary.json'
  if not s.exists():continue
  item={'stage':name,'summary':json.loads(s.read_text()),'assessment':json.loads((p/'assessment.json').read_text()) if (p/'assessment.json').exists() else None,'records':[json.loads(x) for x in (p/'protocol.jsonl').read_text().splitlines()] if (p/'protocol.jsonl').exists() else []};stages.append(item)
 data=json.dumps(stages).replace('<','\\u003c')
 page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>How to win agents and influence swarms · Scale pilot</title><style>
 :root{color-scheme:dark;font:16px/1.55 system-ui;background:#0b1220;color:#e3edf7}body{max-width:1180px;margin:40px auto;padding:0 24px}h1{font-size:38px;line-height:1.15;max-width:850px}h2{font-size:23px;margin-top:36px}p{max-width:900px;color:#b8c8d9}.eyebrow{color:#73d7ce;letter-spacing:.12em;font-size:12px;text-transform:uppercase}a{color:#8cceff}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;padding:11px;border-bottom:1px solid #2b3a50}th{color:#8fa9bf}button,select{background:#182940;color:#e3edf7;border:1px solid #38506b;border-radius:6px;padding:9px;margin:5px}input{width:52%;vertical-align:middle}.panel{background:#111e30;border:1px solid #263a50;border-radius:12px;padding:22px;margin:20px 0}.grid{display:grid;grid-template-columns:1.1fr 1fr;gap:22px}.good{color:#80ddba}.bad{color:#ffbd9a}.muted{color:#8fa9bf}#counter{white-space:nowrap;display:inline-block}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.55 ui-monospace;max-height:430px;overflow:auto}svg{width:100%;max-height:520px}circle{cursor:pointer}small{color:#91a9c0}@media(max-width:800px){.grid{grid-template-columns:1fr}h1{font-size:28px}body{padding:0 14px}table{font-size:12px}}
 </style><div class="eyebrow">Swarm Lab · Native model evidence · One paired procurement world</div><h1>How to win agents and influence swarms</h1><p id="lead"></p><div class="panel"><b>Read the experiment correctly</b><p>The configurations change model, team size and chair compute settings together. Agent calls are dependent. This pilot tests execution and an influence mechanism on one authored scenario; it cannot establish a general effect or isolate team size. All vendors and records are synthetic.</p><a href="PILOT.md">Prospective pilot plan</a> · <a href="DECISION-DIAGNOSTIC.md">Qualification and repair plans</a></div>
 <h2>Qualification history, including failures</h2><table><thead><tr><th>Attempt</th><th>Valid / planned</th><th>Decision gate</th><th>Reported model cost</th><th>Meaning</th></tr></thead><tbody id="history"></tbody></table>
 <h2>Paired pilot outcomes</h2><div id="outcomes"></div><h2>Replay the observed agents</h2><p>Every step is a saved model response. Lines show the fixed two-neighbor graph. Revisions use the agent’s own initial report and its neighbors’ initial reports. Dark nodes have no response at this replay position; light gray means DEFER. Select a node to inspect its actual output.</p><div class="panel"><select id="run"></select><select id="condition"></select><button id="play">Play</button><input type="range" id="step" min="0" value="0"><span id="counter"></span><div class="grid"><svg id="graph" viewBox="0 0 560 540" aria-label="Observed agent response graph"></svg><div><div id="legend"></div><pre id="detail">Choose a node to inspect its recorded response.</pre></div></div></div>
 <h2>What the evidence supports</h2><p>Source extraction, model choice and the deterministic action guard are measured separately. A guard refusal does not mean the model reasoned correctly. A successful repair cohort does not erase the earlier failed qualification. The pilot preserves raw advice, source citations, changes of preference, the final decision table and guarded outcomes.</p><p id="cost"></p><small>Generated only from saved native records. No synthetic agent messages, imputed missing responses or animation of unobserved decisions.</small>
 <script>const data=DATA;const $=s=>document.querySelector(s);const pilots=data.filter(d=>d.stage.startsWith('SP-'));const colors={Aster:'#f493b0',Birch:'#82b5ff',Cobalt:'#65d7c3',DEFER:'#b6b8c3'};const cell=(tr,v,cls)=>{let t=document.createElement('td');t.textContent=v;if(cls)t.className=cls;tr.append(t)};
 $('#lead').textContent=pilots.length?`${pilots.length} native scale configuration(s) recorded. Inspect completion and qualification separately below.`:'Development diagnostics recorded; no native scale pilot has completed yet.';
 for(const d of data.filter(x=>!x.stage.startsWith('SP-'))){let tr=document.createElement('tr'),s=d.summary,a=d.assessment;cell(tr,d.stage);cell(tr,`${s.valid} / ${s.planned}`);cell(tr,a?(a.qualified?'Passed declared gate':'Not qualified'):'Evidence-uptake diagnostic',a?.qualified?'good':'bad');cell(tr,s.actual_usd==null?'Unknown':`$${s.actual_usd.toFixed(6)}`);cell(tr,s.failed?'Acquisition failure retained':a?.qualified?'Development check only':'Valid responses may contain scientific errors');$('#history').append(tr)}
 for(const d of pilots){let box=document.createElement('div');box.className='panel';let h=document.createElement('h3');h.textContent=`${d.summary.team_size} agents · ${d.stage} · ${d.summary.valid}/${d.summary.planned} valid calls`;box.append(h);let table=document.createElement('table');let head=document.createElement('tr');for(const x of ['Condition','Target advice: initial → revised','Deferrals: initial → revised','Raw final choice','Acceptable?','Guard action'])cell(head,x);table.append(head);for(const r of d.assessment.outcomes){let tr=document.createElement('tr');cell(tr,r.condition==='omission'?'Advocacy':'Clean');cell(tr,`${r.initial.target_preferences}/${r.initial.count} → ${r.revised.target_preferences}/${r.revised.count}`);cell(tr,`${r.initial.choices.DEFER||0}/${r.initial.count} → ${r.revised.choices.DEFER||0}/${r.revised.count}`);cell(tr,r.raw_chair?.choice||'Missing');cell(tr,r.raw_evaluation?(r.raw_evaluation.acceptable_decision?'Yes':'No'):'Missing');cell(tr,r.guard?.action||'Missing');table.append(tr)}box.append(table);let p=document.createElement('p');p.textContent=`Reported cost ${d.summary.actual_usd==null?'unknown':'$'+d.summary.actual_usd.toFixed(6)}; ${d.summary.failed} failure, ${d.summary.unstarted} unstarted calls. One independent world.`;box.append(p);$('#outcomes').append(box)}
 if(!pilots.length)$('#outcomes').textContent='Not collected. No model effects are inferred from offline tests.';
 for(const d of pilots){let o=document.createElement('option');o.value=d.stage;o.textContent=d.stage+' · '+d.summary.team_size+' agents';$('#run').append(o)}
 for(const [k,c] of Object.entries(colors)){let x=document.createElement('span');x.textContent='● '+k+'  ';x.style.color=c;$('#legend').append(x)}
 let timer=null;function chosen(){return pilots.find(d=>d.stage===$('#run').value)}function records(){let d=chosen();return d?d.records.filter(r=>r.condition===$('#condition').value):[]}function reset(){let d=chosen();$('#condition').replaceChildren();for(const w of d?d.assessment.outcomes.map(r=>r.condition):[]){let o=document.createElement('option');o.value=w;o.textContent=w==='omission'?'Advocacy':'Clean';$('#condition').append(o)}$('#step').value=0;draw()}
 function draw(){const d=chosen(),rr=records();$('#step').max=rr.length;const k=Number($('#step').value);$('#counter').textContent=`${k} / ${rr.length} responses`;if(k>0)$('#detail').textContent=JSON.stringify(rr[k-1],null,2);let svg=$('#graph');svg.replaceChildren();if(!d)return;const n=d.summary.team_size-2,last={};for(const r of rr.slice(0,k))last[r.agent]=r;const ns='http://www.w3.org/2000/svg',el=(tag,attr)=>{let e=document.createElementNS(ns,tag);for(const [k,v]of Object.entries(attr))e.setAttribute(k,v);svg.append(e);return e};const xy=i=>[280+215*Math.cos(2*Math.PI*i/n-Math.PI/2),265+215*Math.sin(2*Math.PI*i/n-Math.PI/2)];for(let i=0;i<n;i++){let a=xy(i),b=xy((i+1)%n);el('line',{x1:a[0],y1:a[1],x2:b[0],y2:b[1],stroke:'#32485e','stroke-width':1})}const node=(id,label,x,y,r)=>{let row=last[id],choice=row?.answer.choice;let c=el('circle',{cx:x,cy:y,r,fill:row?(colors[choice]||'#d9adfa'):'#243447',stroke:rr[k-1]?.agent===id?'#ffe4a0':'#91a9c0','stroke-width':rr[k-1]?.agent===id?3:1});let t=el('text',{x,y:y+4,'text-anchor':'middle',fill:'#0b1220','font-size':n>20?9:12});t.textContent=label;t.setAttribute('pointer-events','none');c.onclick=()=>$('#detail').textContent=row?JSON.stringify(row,null,2):id+': no response at this position'};for(let i=0;i<n;i++){let [x,y]=xy(i);node('adviser-'+String(i).padStart(2,'0'),String(i),x,y,n>20?11:20)}node('auditor','Audit',280,225,28);node('chair','Chair',280,305,28)}
 $('#run').onchange=reset;$('#condition').onchange=()=>{$('#step').value=0;draw()};$('#step').oninput=draw;$('#play').onclick=()=>{if(timer){clearInterval(timer);timer=null;$('#play').textContent='Play';return}$('#play').textContent='Pause';timer=setInterval(()=>{let s=$('#step');if(+s.value>=+s.max){clearInterval(timer);timer=null;$('#play').textContent='Play';return}s.value=+s.value+1;draw()},400)};reset();$('#cost').textContent='Original cumulative experiment cap: $8. Conservative reservations include previous attempts and unknown charges; reported costs in this page are not the remaining spending allowance. See the closeout for the reconciled ledger.';
 </script></html>'''.replace('DATA',data)
 pilot_plans=[d['summary']['public_plan'] for d in stages if d['stage'].startswith('SP-')]
 page=page.replace('href="PILOT.md"','href="'+(pilot_plans[0] if pilot_plans else 'https://github.com/dmarzzz/swarm-lab/blob/main/researchers/vishesh/notes/influence-swarms/scenario/scale-up/PILOT.md')+'"').replace('href="DECISION-DIAGNOSTIC.md"','href="https://github.com/dmarzzz/swarm-lab/blob/main/researchers/vishesh/notes/influence-swarms/scenario/scale-up/DECISION-DIAGNOSTIC.md"')
 out=BASE/'scale-up/report.html';out.write_text(page);print(json.dumps({'saved_data_stages':len(stages),'pilot_stages':len([s for s in stages if s['records']]),'path':str(out),'model_calls':0}))
if __name__=='__main__':render()
