"""Render only recorded instrument events; this view never constructs actor inputs."""
import json
from pathlib import Path

def render(data,path):
 embedded=json.dumps(data).replace('<','\\u003c')
 template='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Phantom Coast · population instrument</title>
<style>
:root{font-family:Inter,system-ui,sans-serif;color:#dce8f1;background:#09131c}*{box-sizing:border-box}body{margin:0;padding:28px;max-width:1280px;margin:auto}h1{font-size:32px;margin:10px 0}h2{font-size:17px;margin:0 0 14px}.eyebrow{color:#58d4bf;text-transform:uppercase;letter-spacing:.15em;font-size:12px}.muted{color:#9cabb8;font-size:14px;line-height:1.55}.warning{border:1px solid #ba8544;background:#2e2318;color:#ffe0ad;padding:13px 17px;border-radius:8px;margin:18px 0}.controls{display:flex;gap:16px;flex-wrap:wrap;align-items:center;margin:24px 0}select,button{background:#203442;color:#e6f0f5;border:1px solid #49606e;border-radius:6px;padding:10px;font:inherit}input{accent-color:#58d4bf;width:200px}.grid{display:grid;grid-template-columns:1fr 2fr;gap:18px}.panel{background:#10212d;border:1px solid #29404f;border-radius:12px;padding:20px}.tiles{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.tile{text-align:center;border-radius:6px;padding:13px 3px;color:#fff;font-size:12px;border:2px solid transparent}.LAND{background:#346f53}.WATER{background:#24557f}.UNKNOWN{background:#51565e}.missing,.failed,.invalid{background:repeating-linear-gradient(45deg,#5b3137,#5b3137 5px,#39232b 5px,#39232b 10px)}.focus{border-color:#f4b65d}.agent{display:grid;grid-template-columns:100px 1fr;align-items:center;gap:12px;margin:10px 0}.seed{color:#f4b65d}.stats{display:flex;gap:30px;flex-wrap:wrap;padding:20px 0}.stat b{font-size:27px;display:block}.stat span{font-size:12px;color:#9cabb8}pre{font-size:12px;white-space:pre-wrap;word-break:break-word;color:#c6d7e1}details{margin-top:18px;border-top:1px solid #29404f;padding-top:12px}.events{line-height:1.8;font-size:14px}.row{margin-top:18px}.chip{background:#243c4c;padding:3px 6px;border-radius:4px}footer{margin-top:20px;color:#9cabb8;font-size:12px}@media(max-width:750px){body{padding:16px}.grid{grid-template-columns:1fr}.agent{grid-template-columns:70px 1fr}.tile{font-size:10px}}
</style><div class="eyebrow">Phantom Coast / PC11</div><h1>What ten GPT-6 Sol agents did with one false report</h1><div class="muted">Population exploration instrument · ten separate contexts · two collective inspections · four matched conditions</div>
<div class="warning" id="warning"></div><div class="controls"><label>Condition <select id="arm"></select></label><label>Time <input id="time" type="range" min="0" max="2" value="0"></label><button id="play">Play</button><span id="phase"></span></div>
<div class="grid"><section class="panel"><h2>World truth · evaluator only</h2><div id="truth" class="tiles"></div><p class="muted">Amber outline: the reported location. This marker and world truth never enter actor context.</p><h2>Evidence and inspections</h2><div id="events" class="events"></div><div class="stats" id="stats"></div><p class="muted">Loss: wrong 1 · UNKNOWN .25 · correct 0. Missing answers remain bounded, never treated as correct.</p></section><section class="panel"><h2>Each actor’s expressed map</h2><div id="agents"></div><div id="score" class="stats"></div><div class="muted">Green = LAND · blue = WATER · gray = UNKNOWN · striped = invalid/missing/failed. Maps are visible outputs, not measurements of hidden internal beliefs.</div></section></div>
<section class="panel row"><h2>Delivered information</h2><label>Inspect actor <select id="actor"></select></label><div id="delivery" class="events row"></div><details><summary>Exact saved packet and response</summary><pre id="packet"></pre></details></section>
<footer>Four native matched branches from one synthetic world. Ten contexts per arm are dependent observations, not independent sample units. Exposure ancestry records delivery, not hidden beliefs or causal mediation. Every frame is rebuilt from saved model decisions.</footer>
<script>const data=DATA; const $=s=>document.getElementById(s);const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let timer=null;
$('warning').textContent=data.warning;
data.episodes.forEach((e,i)=>$('arm').add(new Option((e.condition.poison?'False':'Honest')+' report · peers '+(e.condition.peers?'ON':'OFF'),i)));
for(let i=0;i<10;i++)$('actor').add(new Option('agent-'+i,'agent-'+i));
function tiles(map,e,status='valid'){return Object.keys(e.world.truth).map(s=>{let v=map?.[s]||status;return `<div class="tile ${esc(v)} ${s===e.world.target?'focus':''}">${esc(s)}<br><b>${esc(v)}</b></div>`}).join('')}
function draw(){let e=data.episodes[+$('arm').value],t=+$('time').value,turn=e.turns[t],s=e.summary.timeline[t];$('phase').textContent=['Initial report / before inspection 1','After inspection 1 / before inspection 2','Final / after inspection 2'][t];$('truth').innerHTML=tiles(e.world.truth,e);$('agents').innerHTML=turn.entries.map(x=>`<div class="agent"><span class="${x.agent===e.world.seed_actor?'seed':''}">${esc(x.agent)}${x.agent===e.world.seed_actor?'<br><small>seed recipient</small>':''}</span><div class="tiles">${tiles(x.decision?.map,e,x.status)}</div></div>`).join('');let prior=e.turns.filter(x=>x.time<t&&x.receipt);let seed=e.turns[0].entries.find(x=>x.agent===e.world.seed_actor).packet.private_reports[0];$('events').innerHTML=`Seed report: <span class="chip">${esc(seed.site)} = ${esc(seed.label)}</span><br>`+prior.map(x=>`Inspection ${x.time+1}: ${esc(x.receipt.site)} → ${esc(x.receipt.label)} (${esc(x.slot)})`).join('<br>')+`<hr>Next selected inspection: <b>${esc(turn.selected??(t===2?'none — final':'none — failed slot'))}</b>`;$('stats').innerHTML=`<div class="stat"><b>${new Set(prior.map(x=>x.selected)).size}/4</b><span>locations observed so far</span></div>`;$('score').innerHTML=`<div class="stat"><b>${s.unexposed_target.wrong}/9</b><span>initially unseeded agents wrong at reported site</span></div><div class="stat"><b>${s.unexposed_target.unknown}/9</b><span>initially unseeded agents UNKNOWN</span></div><div class="stat"><b>${s.mean_loss_bounds.map(v=>v.toFixed(2)).join(' – ')}</b><span>mean map loss bounds</span></div>`;let a=turn.entries.find(x=>x.agent===$('actor').value);$('delivery').textContent=a.exposure_ancestors.length?'Visible record / prior-map IDs: '+a.exposure_ancestors.join(', '):'No prior evidence or peer map delivered at this time.';$('packet').textContent=JSON.stringify(a,null,2)}
['arm','time','actor'].forEach(id=>$(id).addEventListener('input',draw));$('play').onclick=()=>{if(timer){clearInterval(timer);timer=null;$('play').textContent='Play';return}if(+$('time').value===2)$('time').value=0;draw();$('play').textContent='Pause';timer=setInterval(()=>{let t=+$('time').value;if(t===2){clearInterval(timer);timer=null;$('play').textContent='Play'}else{$('time').value=t+1;draw()}},1300)};draw();</script></html>'''
 Path(path).write_text(template.replace('DATA',embedded))
